# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42c82d098c0f0f073b642d92f7196d75a090b53623c6c9c0edf0171b67e18e538b0b2bab014448ffd2745ad6bb166a3e7ee82e901fddfeeada4f2406780f5277

test:
  secret_key_base: 3fd955da98feb4c6ed513afedcc0176479978a54b31c1cfdd0a3af0d112048b38e0e02db34855c0e46e25ce0b66cf2a0ea6eeb1d25077b9d1c2f51eaf1c21ac7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
